# Generated by Django 4.2.9 on 2024-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='jobs',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
