# Generated by Django 4.2.9 on 2024-04-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_jobs_options_jobs_created'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='maxapplicant',
        ),
    ]
