# Generated by Django 4.2.9 on 2024-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_myuser_managers_remove_jobs_maxapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.TextField(),
        ),
    ]
