# Generated by Django 4.2.9 on 2024-04-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='resume',
            field=models.FileField(null=True, upload_to='user_resume/'),
        ),
    ]
